### ISSUE TITLE
Did you train the PECNet or Trajectron++ on the SportVU dataset?

### ISSUE THREAD

**Issue by noparkee** [amazon-research/explainable-trajectory-prediction#5]
Thank you for your hard work!

There is only a code that trains _Trajectron++Edge_.
Did you train the PECNet or Trajectron++ on the SportVU datset when obtaining Table 1 in your paper??
Then, how can I train these baseline models on the SportVU?

**Comment by noparkee** [comment]
And I have one more question,.
In `src/explainable_trajectory_prediction/trajectron/train.py`, you imported some modules by 
```python
import model.dataset as third_party_dataset
import model.model_registrar as model_registrar
```

In this code, what is the `model` or where is the `model` ?`

**Comment by os1a** [comment]
Hi,

Thanks for your questions and your interest in our paper.

Regarding your first question, yes we trained the original PECNet and Trajectron++ on the SportVU dataset. You can use their original code for that purpose and the processed SportVU dataset that can be obtained using the pre-processing tools we provided (under `Data Preparation` of the README):
```
python tools/prepare_data.py
python tools/process_trajectron_data.py
python tools/process_pecnet_data.py
```

For your second question, these are coming from the Trajectron++ repository. As explained in the README, you need to download the thirdparty code of Trajectron++ and place it under:
```
thirdparty/Trajectron-plus-plus
```
Then you can use any of the scripts by appending the python environment as:
```
env PYTHONPATH=src:thirdparty/Trajectron_plus_plus/trajectron:thirdparty/PECNet/utils python3 
```
So the `model` is coming from `thirdparty/Trajectron_plus_plus/trajectron`

Hope this helps,
Best,

**Comment by noparkee** [comment]
Thank you for your detailed answer!

Based on your answer, I tried training the original trajectron++ on nba dataset.
First, I tried using the config file from the original trajectron++ but it doesn't work, so I used the config file which is from this repository `explainable-trajectory-prediction/models/trajectron/sport/orig/config.json`
Is this right?

Thank you again!

**Comment by os1a** [comment]
Yes, for training the original trajectron++, you can use that config. For training our variant (edge), you can use the edge config file.

Best,

**Comment by noparkee** [comment]
Thank you so much !!
